// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package model

import (
	"context"
)

type Querier interface {
	REMOVEME(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
