// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package model

import (
	"context"
)

const rEMOVEME = `-- name: REMOVEME :exec
SELECT 1
`

func (q *Queries) REMOVEME(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, rEMOVEME)
	return err
}
