// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package model

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	GetUserByID(ctx context.Context, id string) (*User, error)
	RemoveUserByID(ctx context.Context, id string) error
	UpdateUserByID(ctx context.Context, arg *UpdateUserByIDParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
