// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func initialize() (*app, error) {
	mainApp := &app{}
	return mainApp, nil
}

// wire.go:

type app struct{}
