name: Lint
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-lint
  cancel-in-progress: true
jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
  buf:
    name: buf
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true
      - name: buf format
        run: go run github.com/bufbuild/buf/cmd/buf format -w
      - name: git diff check
        run: git diff --exit-code --quiet proto/*
  devenv:
    name: devenv
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - run: nix profile install github:cachix/devenv/latest
        shell: sh
      - name: devenv ci
        run: devenv ci
  eclint:
    name: eclint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: eclint
        uses: reviewdog/action-eclint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          filter_mode: nofilter
          reporter: github-pr-review
  gomod:
    name: gomod
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true
      - name: go mod tidy
        run: go mod tidy
      - name: git diff check
        run: git diff --exit-code --quiet
  gomock:
    name: gomock
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true
      - name: gomock generate
        run: make generate.mock
      - name: git diff check
        run: git diff --exit-code --quiet domain/*
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-review
          hadolint_flags: Dockerfile
  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          exclude: |
            ./go.*
  wire:
    name: wire
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true
      - name: wire generate
        run: make generate.wire
      - name: git diff check
        run: git diff --exit-code --quiet cmd/app/wire_gen.go
