name: Lint
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-lint
  cancel-in-progress: true
jobs:
  eclint:
    name: eclint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: eclint
        uses: reviewdog/action-eclint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          filter_mode: nofilter
          reporter: github-pr-review
  gomock:
    name: gomock
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: gomock generate
        run: make generate.mock
      - name: git diff check
        run: git diff --exit-code --quiet domain/*
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-review
          hadolint_flags: Dockerfile
  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          exclude: |
            ./go.*
  wire:
    name: wire
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: wire generate
        run: make generate.wire
      - name: git diff check
        run: git diff --exit-code --quiet cmd/app/wire_gen.go
